### ISSUE TITLE
Use CSS :empty selector and :after pseudo-element for placeholders

### ISSUE THREAD

**Issue by alfredxing** [jakiestfu/Medium.js#3]
Would it be possible to use `:empty` and `:after` to do the placeholders?
Like so:

``` css
#editor:empty:after {
    content: 'My Placeholder'; /* Changed/inserted with JavaScript */
}
```

This would probably be faster than using a `key` listener.

(In CSS 3 the 'official' way to use `:after` is actually `::after`, but more browsers support the older version).
